run:
	@python caesar/__init__.py

hole:
	@python caesar/hole_detector.py

profit:
	@python caesar/profit.py

setup:
	@pip install -r requirements.txt

balance:
	@python caesar/balance.py

test:
	@python caesar/test.py
